import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import FBShare from '../components/FBShare'
import FBLoginPrompt from '../components/FBLoginPrompt'
import FBLoginStatus from '../components/FBLoginStatus'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>meta-tracking test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       {/* https://developers.facebook.com/quickstarts/671368507898087/?platform=web */}
      <Script id="fb"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            window.fbAsyncInit = function() {
              FB.init({
                appId      : '1495224634333441',
                xfbml      : true,
                version    : 'v15.0'
              });
              FB.AppEvents.logPageView();
            };
            (function(d, s, id){
               var js, fjs = d.getElementsByTagName(s)[0];
               if (d.getElementById(id)) {return;}
               js = d.createElement(s); js.id = id;
               js.src = "https://connect.facebook.net/en_US/sdk.js";
               fjs.parentNode.insertBefore(js, fjs);
             }(document, 'script', 'facebook-jssdk'));`}} />


      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <a href="https://developers.facebook.com/apps/1495224634333441/"><h1>Facebook developer test-app</h1></a>
          <FBLoginStatus />
        </div>
        <div>
        </div>

        <div>
          <FBShare />
          <FBLoginPrompt />
        </div>

      </main>
    </>
  )
}
