import Image from "next/image";
import Head from "next/head";

import { useFBAppState } from "@/contexts/FBAppState";
import { APP_ID } from "@/config/environment";
import FBRevokePermissions from "@/components/FBRevokePermissions";

import styles from "../styles/Home.module.css";
import FBShare from "../components/FBShare";
import FBLogout from "../components/FBLogout";
import FBLoginStatus from "../components/FBLoginStatus";
import FBLoginPrompt from "../components/FBLoginPrompt";

export default function Home() {
  const { FBStatus } = useFBAppState();
  return (
    <>
      <Head>
        <title>meta-tracking test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <a href={`https://developers.facebook.com/apps/${APP_ID}/`}>
            <h1>Facebook developer test-app</h1>
          </a>
          <FBLoginStatus />
        </div>
        <div></div>

        <div>
          <FBShare />
          <FBLoginPrompt scope="" label="Basic Login" />
          <FBLoginPrompt scope="email" label="Email Login" />
          <FBLoginPrompt
            scope="email, user_friends"
            label="Email + Friends Login"
          />
          <FBLoginPrompt
            scope="email,user_birthday, user_age_range,user_friends, user_gender, user_location"
            label="Full Login"
          />
          <FBRevokePermissions />
          {FBStatus && FBStatus.status && FBStatus.status === "connected" && (
            <FBLogout />
          )}
        </div>
      </main>
    </>
  );
}
